# Train/val/test sets
train: 'data/images/train'
val: 'data/images/validation'
test: 'data/images/test'

# Classes
names:
  0: Black Background
  1: Abdominal Wall
  2: Liver
  3: Gastrointestinal Tract
  4: Fat
  5: Grasper
  6: Connective Tissue
  7: Blood
  8: Cystic Duct
  9: L-hook Electrocautery
  10: Gallbladder
  11: Hepatic Vein
  12: Liver Ligament